### ISSUE TITLE
[Bug] EyesUtils.getCurrentFrameContentEntireSize(..) gets too big page width

### ISSUE THREAD

**Issue by By-ivan** [applitools/eyes.sdk.java3#46]
During visual test on the page **https://www.nicorette.es/productos** occurs exception with stack trace 

> Caused by: java.lang.OutOfMemoryError: Java heap space
>        at java.awt.image.DataBufferByte.<init>(Unknown Source) ~[?:1.8.0_152]
> 	at java.awt.image.Raster.createInterleavedRaster(Unknown Source) ~[?:1.8.0_152]
> 	at java.awt.image.BufferedImage.<init>(Unknown Source) ~[?:1.8.0_152]
> 	at com.applitools.eyes.selenium.capture.FullPageCaptureAlgorithm.getStitchedRegion(FullPageCaptureAlgorithm.java:166) ~[eyes-selenium-java3-3.29.jar:?]
> 	at com.applitools.eyes.selenium.Eyes.getScreenshot(Eyes.java:1989) ~[eyes-selenium-java3-3.29.jar:?]
> 	at com.jjconsumer.dte.selenium.eyes.AbstractCroppingEyes.getScreenshot(AbstractCroppingEyes.java:25) ~[visual-testing-0.5.1.jar:0.5.1]
> 	at com.applitools.eyes.EyesBase.getAppOutputWithScreenshot(EyesBase.java:1558) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.EyesBase.access$000(EyesBase.java:34) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.EyesBase$2.getAppOutput(EyesBase.java:1276) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.MatchWindowTask.tryTakeScreenshot(MatchWindowTask.java:169) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.MatchWindowTask.takeScreenshot(MatchWindowTask.java:125) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.MatchWindowTask.matchWindow(MatchWindowTask.java:100) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.EyesBase.matchWindow(EyesBase.java:1067) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.EyesBase.checkWindowBase(EyesBase.java:1020) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.EyesBase.checkWindowBase(EyesBase.java:984) ~[eyes-sdk-core-java3-3.29.jar:?]
> 	at com.applitools.eyes.selenium.Eyes.checkRegion(Eyes.java:862) ~[eyes-selenium-java3-3.29.jar:?]

The root cause here is : https://github.com/applitools/eyes.sdk.java3/blob/master/eyes.selenium.java/src/main/java/com/applitools/eyes/selenium/EyesSeleniumUtils.java#L257
The method returns too big width as 999000. 

**Steps to reproduce:** 
Perform visual check against page **https://www.nicorette.es/productos**

Please see attached screenshot:
![1](https://user-images.githubusercontent.com/17816729/35033473-d6511864-fb7b-11e7-8867-fa15454f21b3.png)

CC's @valfirst

**Comment by danielputerman** [comment]
Thanks, looking into that now.

**Comment by By-ivan** [comment]
Hi, @danielputerman
Is there any issue updates you can share ?

**Comment by valfirst** [comment]
@danielputerman, @itaibh, do you plan to fix this issue? otherwise we can start developing custom fork

**Comment by itaibh** [comment]
@By-ivan , @valfirst  - Sorry for the delay. We are working on it and we believe we have found how to solve it. @danielputerman will be able to tell you how long you can expect for a new version, but I'll try to push a fix soon.
Again, sorry for the long wait, and thank you for the report.

**Comment by By-ivan** [comment]
Hi guys @danielputerman  @itaibh 
We are still in need of ETA on the issue.

**Comment by valfirst** [comment]
@danielputerman @itaibh  do you have any updates?

**Comment by danielputerman** [comment]
Same fix as for https://github.com/applitools/eyes.sdk.java3/issues/31
