### ISSUE TITLE
eyes.checkWindow does not work on real device Android 7

### ISSUE THREAD

**Issue by selenUser** [applitools/eyes.sdk.java3#5]
environment:
`compile (group: 'com.applitools', name: 'eyes-selenium-java', version: '2.56')
compile (group:'io.appium', name: 'java-client', version: '5.0.0-BETA6'`

Device API level: 24

when running `eyes.checkWindow(screenshotName);`, I'm getting this error message:
`2017-04-04 16:01:04:860 - info: [debug] [ADB] Running 'C:\Android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","*****","pull","/data/local/tmp/screenshot.png","C:\\Users\\AppData\\Local\\Temp\\appium11734-2284-1qrcp4n.brb3k81tt9.png"]
2017-04-04 16:01:04:948 - error: [MJSONWP] Encountered internal error running command: Error: Unsupported MIME type: 
    at Jimp.throwError (C:\Users\AppData\Roaming\npm\node_modules\appium\node_modules\jimp\index.js:82:43)
    at Jimp.parseBitmap (C:\Users\AppData\Roaming\npm\node_modules\appium\node_modules\jimp\index.js:307:31)
    at C:\Users\AppData\Roaming\npm\node_modules\appium\node_modules\jimp\index.js:200:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)`

according to [appium site](https://github.com/appium/appium/issues/7853) they said to save screenshot like `byte[] screenshot = getDriver().getScreenshotAs(OutputType.BYTES);` and in your project I see `String screenshot64 = driver.getScreenshotAs(OutputType.BASE64);`

if not exact can you please let me know how to make it work ?
my code:
`batchInfo = new BatchInfo(name);
 eyes = new Eyes();
 eyes.setBatch(batchInfo);
 eyes.setApiKey(EYES_API_KEY);
 eyes.setMatchLevel(MatchLevel.LAYOUT2);
 eyes.setSaveNewTests(false);
 eyes.open(driver, appName, testName);
 eyes.checkWindow(screenshotName);`

Thanks in advance

**Comment by danielputerman** [comment]
Hi, thanks for the feedback! The link you were referring was related to moving from getting the image as bytes instead of as File, not from base64. To be honest, I'm not sure what the problem is in either case, as from my experience, the image is always retrieved as base64 via the wire protocol anyway, and only then decoded into bytes/saved to a file 😄. Anyway, I'll check and update.

**Comment by selenUser** [comment]
it was a device issue, I tried on another device and it worked
